---
- name: Destroy old kubernetes manifests
  become: yes
  file: 
          path: /etc/kubernetes
          state: absent

- name: Destroy the kubelet file
  become: yes
  file:
          path: /etc/default/kubelet
          state: absent

- name: Destroy old etcd
  become: yes
  file:
          path: /var/lib/etcd
          state: absent

- name: Add apt signing key for k8s
  apt_key:
          url: "{{ gpgkey }}"
          state: present

- name: Add apt repository for stable version
  apt_repository:
          repo: "{{ repo }}"
          state: present
          filename: kubernetes.list

- name: Install k8s
  apt:
          name: "{{ packages }}"
          state: present
          update_cache: yes

- name: Create /etc/default/kubelet if it doesn't exist
  file:
          path: /etc/default/kubelet
          state: touch

- name: Configure node ip
  lineinfile:
          path: /etc/default/kubelet
          regexp: '^KUBELET_EXTRA_ARGS.*$'
          line: "KUBELET_EXTRA_ARGS=\"--cgroup_driver=systemd --node-ip={{ node_ip }}\""

- name: Restart kubelet
  service:
          name: kubelet
          daemon_reload: yes
          state: restarted
