---
install_packages:
  - ntp
  - ntpdate
  - openssl
  - docker.io

remove_packages:
  - snapd
  - squashfs-tools

snap_mounts: "/var/lib/snapd/snaps/*.snap"

cmdline_file: /boot/firmware/cmdnline.txt

nobtcmd_file: /boot/firmware/nobtcmd.txt

k3s_install_cmd: "curl -sfL https://get.k3s.io | sh -"

k3s_install_opts: " --no-deploy servicelb --no-deploy traefik --cluster-init"

k3s_node_token_path: /var/lib/rancher/k3s/server/node-token
