---
- name: Install K3s on the master server
  shell: "{{ k3s_install_cmd }}"
  when: inventory_hostname in groups['k3s_master']

- name: Get the token from the master
  slurp:
    src: "{{ k3s_node_token_path }}"
  register: token
  when: inventory_hostname in groups['k3s_master']

- name: Capture the token
  set_fact: node_token="{{ token.content | b64decode }}"
  when: inventory_hostname in groups['k3s_master']

- name: Show off the token
  debug:
    msg: "{{ hostvars['master']['node_token'] }}"

- name: Join k3s nodes to the cluster
  shell: "{{ k3s_install_cmd }}"
  environment:
    K3S_URL: "https://{{ hostvars['master']['hostname'] }}:6443"
    K3S_TOKEN: "{{ hostvars['master']['node_token'] }}"
  when: inventory_hostname in groups['k3s_nodes']
