---
- name: Add the ubuntu user to the sudoers
  become: true
  copy:
    dest: "/etc/sudoers.d/ubuntu"
    content: "ubuntu ALL=(ALL) NOPASSWD: ALL"

- name: Deploy the SSH key
  become: true
  authorized_key: user=ubuntu
                  key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
                  state=present

- name: Disable password authentication
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: true
  notify:
    - restart ssh

- name: Disable root login
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: true
  notify:
    - restart ssh

- name: Set the hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure that the loopback is named
  replace:
    dest: /etc/hosts
    regexp: localhost
    replace: '{{ inventory_hostname }}'
    backup: yes

- name: Add the inventory to /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  with_items:
    - "{{ groups['all'] }}"

- name: Ensure prerequisite packages exist
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true

- name: Remove the swapfile from /etc/fstab
  mount:
    name: [swap, none]
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  
- name: Set swapiness to zero
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    line: vm.swapiness=0

- name: Stop ntpd service
  become: true
  service:
    name: ntp
    state: stopped

- name: Start ntpd service
  become: true
  service:
    name: ntp
    state: restarted
    enabled: true

- name: Test for the cgroup updates 
  command: 'grep cgroup_enable=memory" /boot/firmware/nobtcmd.txt'
  register: cgroup_group
  ignore_errors: true

- name: Set Kernel features for the RPIs (/boot/cmdline.txt)
  lineinfile:
    path: /boot/firmware/nobtcmd.txt
    backrefs: true
    state: present
    regexp: '(.*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  when: cgroup_group.rc == 1

- name: Set GPU memory split to 16MB
  lineinfile:
    path: /boot/config.txt
    line: 'gpu_mem=16'
    create: true

- name: Reboot the system -- RPIs are slow so wait a bit
  reboot:
    reboot_timeout: 300

- name: Download K3s
  get_url: 
    url: https://get.k3s.io
    dest: /opt/setup_k3s.sh
    mode: 0755

    #- name: Setup K3s
  #become: true
  #command: /opt/setup_k3s.sh 
  #environment:
    #K3S_URL: "https://{{ hostvars['master']['ansible_host'] }}:6443"
    #when: inventory_hostname in groups['k3s_master']
