---
- name: Add the ubuntu user to the sudoers
  become: yes
  copy:
    dest: "/etc/sudoers.d/ubuntu"
    content: "ubuntu ALL=(ALL) NOPASSWD: ALL"

- name: Deploy the SSH key
  become: yes
  authorized_key: user=ubuntu
                  key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
                  state=present

- name: Disable password authentication
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: yes
  notify:
    - restart ssh

- name: Disable root login
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: yes
  notify:
    - restart ssh

- name: Set the hostname
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add the inventory to /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  with_items:
    - "{{ groups['all'] }}"

- name: Ensure prerequisite packages exist
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes

- name: Remove the swapfile from /etc/fstab
  mount:
    name: [swap, none]
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  
- name: Set swapiness to zero
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    line: vm.swapiness=0

- name: Stop ntpd service
  become: yes
  service:
    name: ntp
    state: stopped

- name: Start ntpd service
  become: yes
  service:
    name: ntp
    state: restarted
    enabled: yes

- name: Set Kernel features for the RPIs (/boot/cmdline.txt)
  copy:
    dest: "/boot/cmdline.txt"
    content: |
      cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory

- name: Reboot the system -- RPIs are slow so wait a bit
  reboot:
    reboot_timeout: 300
