---
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/{{ distro }}/gpg
    state: present

- name: Add apt repository for the stable version
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ distro }} {{ansible_distribution_release }} stable
    state: present

- name: Install docker and dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes
  notify: 
    - docker status

- name: Ensure Docker cgroup driver is systemd
  become: yes
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }
  notify:
    - docker status

- name: Reboot the system for the cgroup change to take effect
  reboot:

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    group: docker
