---
- name: Add the ubuntu user to the sudoers
  become: yes
  copy:
    dest: "/etc/sudoers.d/ubuntu"
    content: "ubuntu ALL=(ALL) NOPASSWD: ALL"

- name: Deploy the SSH key
  become: yes
  authorized_key: user=ubuntu
                  key=" {{ lookup('file', '~/.ssh/id_rsa.pub') }}"
                  state=present

# - name: Disable password authentication
#  become: yes
#  lineinfile:
#          dest: /etc/ssh/sshd_config
#          regexp: '^PasswordAuthentication'
#          line: "PasswordAuthentication no"
#          state: present
#          backup: yes
#  notify:
#          - restart ssh

- name: Disable root login
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: yes
  notify:
    - restart ssh

- name: Set the hostname
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add the inventory to /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  with_items:
    - "{{ groups['all'] }}"

- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes
